aliases:
  - &update-npm
    name: Update npm to the latest version
    command: sudo npm install -g npm@latest

  - &save-dependencies-cache
    key: v1-dependency-cache-{{ checksum "package.json" }}
    paths:
      - ./node_modules

  - &restore-dependencies-cache
    keys:
      - v1-dependency-cache-{{ checksum "package.json" }}
      - v1-dependency-cache-

  - &filter-all-tags
    tags:
      only: /.*/

defaults: &defaults
  docker:
    - image: circleci/node:10.14.1
  working_directory: ~/erc777

version: 2

jobs:
  install-dependencies:
    <<: *defaults
    steps:
      - run: *update-npm
      - checkout
      - run:
          name: Install npm dependencies with npm ci
          command: npm ci
      - save_cache: *save-dependencies-cache
  test:
    <<: *defaults
    steps:
      - run: *update-npm
      - run: curl https://sh.rustup.rs -sSf | sh -s -- -y
      - run: source ~/.profile && rustup install nightly-2018-11-15
      - run: source ~/.profile && rustup default nightly
      - run: source ~/.profile && rustup target add wasm32-unknown-unknown
      - checkout
      - run: source ~/.profile && cd contracts/pwasm-erc777 && ./build.sh
      - run: source ~/.profile && cd contracts/pwasm-erc777 && ./test.sh
      - restore_cache: *restore-dependencies-cache
      - run:
          name: Test
          command: npm run test

workflows:
  version: 2
  ci_cd:
    jobs:
      - install-dependencies:
          filters: *filter-all-tags
      - test:
          requires:
            - install-dependencies
          filters: *filter-all-tags
